# Generated by Django 2.0.2 on 2018-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('b_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('b_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('p_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('p_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('time_st', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
