# Generated by Django 2.0.2 on 2018-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_queues_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='queues',
            name='device_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='queues',
            name='mk_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='device_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='mk_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='time_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queues',
            name='time_st',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
