# Generated by Django 2.0.2 on 2018-02-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_auto_20180223_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('b_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('b_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('p_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('p_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_tx', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_rx', models.CharField(blank=True, max_length=45, null=True)),
                ('time_st', models.DateTimeField(blank=True, null=True)),
                ('mk_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='queues',
            name='b_rx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='b_tx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='drop_rx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='drop_tx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='mk_time',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='p_rx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='p_tx',
        ),
        migrations.RemoveField(
            model_name='queues',
            name='time_st',
        ),
        migrations.AddField(
            model_name='queue_data',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queues'),
        ),
    ]
