# Generated by Django 2.0.2 on 2018-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_auto_20180223_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_data',
            name='owner',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
