# Generated by Django 2.0.2 on 2018-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_queue_data_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue_data',
            old_name='usage',
            new_name='usage_rx',
        ),
        migrations.AddField(
            model_name='queue_data',
            name='usage_tx',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
