# Generated by Django 2.0.2 on 2018-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_auto_20180313_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_data',
            name='dummy',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='comment',
            field=models.CharField(blank=True, default='0', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='dummy',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
