# Generated by Django 2.0.2 on 2018-03-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0016_queue_data_time_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue_data',
            name='time_delta',
        ),
    ]
