# Generated by Django 2.0.2 on 2018-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0017_remove_queue_data_time_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_data',
            name='average_rx',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='queue_data',
            name='average_tx',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
