# Generated by Django 2.0.2 on 2018-03-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0018_auto_20180316_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
