# Generated by Django 2.0.2 on 2018-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=60, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, max_length=60, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('mac', models.CharField(blank=True, max_length=45, null=True)),
                ('rssi', models.CharField(blank=True, max_length=10, null=True)),
                ('snr', models.CharField(blank=True, max_length=10, null=True)),
                ('ccq_tx', models.CharField(blank=True, max_length=10, null=True)),
                ('ccq_rx', models.CharField(blank=True, max_length=10, null=True)),
                ('uptime', models.CharField(blank=True, max_length=45, null=True)),
                ('time_st', models.DateTimeField(blank=True, null=True)),
                ('mk_time', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, default='0', max_length=45, null=True)),
                ('dummy', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.APs')),
            ],
        ),
    ]
