# Generated by Django 2.0.2 on 2018-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20180321_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='distance',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='uptime_sec',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
