# Generated by Django 2.0.2 on 2018-03-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20180327_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='cust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registrations.Customers'),
            preserve_default=False,
        ),
    ]
