# Generated by Django 2.0.2 on 2018-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registrations_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aps',
            name='device_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='cust_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='device_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
