# Generated by Django 2.0.2 on 2018-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20180402_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('lon_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lat_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aps',
            old_name='device_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='aps',
            name='frequency',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
