# Generated by Django 2.0.2 on 2018-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20180410_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='towers',
            name='loc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
