# Generated by Django 2.0.2 on 2018-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_towers_loc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aps',
            name='loc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
