# Generated by Django 2.0.2 on 2018-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_aps_loc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='ap_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='loc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
