# Generated by Django 2.0.2 on 2018-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20180413_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='loc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
