# Generated by Django 2.0.2 on 2018-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_registrations_loc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='frequency',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
